### PR TITLE
adding code

### PR DESCRIPTION
**Pull request by cvalaas**

### CODE REVIEW

**Comment by cvalaas** [comment]
As long as you have python3 and gcloud installed, this should run right out of the box

**Review by jbuck — APPROVED** [review]
This works great!

**Comment by cvalaas** [comment]
For those wondering why I'm essentially shelling out to `gcloud` instead of using the API, I have reasons available on request (not necessarily _good_ reasons, mind you).

**Comment by jbuck** [comment]
Hah - what are the reasons? want to add them as comments into the code? or file an issue?

**Comment by cvalaas** [comment]
> Hah - what are the reasons? want to add them as comments into the code? or file an issue?

added a comment to the script

**Pull request merged**
